### ISSUE TITLE
导入插件后报错

### ISSUE THREAD

**Issue by ketchup1995** [f0ng/log4j2burpscanner#10]
jdk版本也换过了，是编译的问题吗？？
![图片](https://user-images.githubusercontent.com/87350553/145932572-984a4980-245c-4719-8922-c4f0f4154879.png)
`java.lang.NullPointerException
	at burp.dcb.O(Unknown Source)
	at burp.cz8.getHttpService(Unknown Source)
	at burp.hy.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:149)
	at burp.hmr.a(Unknown Source)
	at burp.bp4.b(Unknown Source)
	at burp.gj_.a(Unknown Source)
	at burp.gj_.a(Unknown Source)
	at burp.dmr.a(Unknown Source)
	at burp.cup.a(Unknown Source)
	at burp.ifl.a(Unknown Source)
	at burp.dmr.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:754)
	at burp.gm0.a(Unknown Source)
	at burp.gm0.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(JTabbedPane.java:828)
	at burp.d0z.a(Unknown Source)
	at burp.cup.a(Unknown Source)
	at burp.cup.b(Unknown Source)
	at burp.d0w.a(Unknown Source)
	at burp.iew.addSuiteTab(Unknown Source)
	at burp.fvi.addSuiteTab(Unknown Source)
	at burp.exn.addSuiteTab(Unknown Source)
	at burp.BurpExtender$1.run(BurpExtender.java:292)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at burp.dcb.O(Unknown Source)
	at burp.cz8.getHttpService(Unknown Source)
	at burp.hy.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:149)
	at burp.hmr.a(Unknown Source)
	at burp.bp4.b(Unknown Source)
	at burp.gj_.a(Unknown Source)
	at burp.gj_.a(Unknown Source)
	at burp.dmr.a(Unknown Source)
	at burp.cup.a(Unknown Source)
	at burp.ifl.a(Unknown Source)
	at burp.dmr.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:754)
	at burp.gm0.a(Unknown Source)
	at burp.gm0.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(JTabbedPane.java:828)
	at burp.d0z.a(Unknown Source)
	at burp.cup.a(Unknown Source)
	at burp.cup.b(Unknown Source)
	at burp.d0w.a(Unknown Source)
	at burp.iew.addSuiteTab(Unknown Source)
	at burp.fvi.addSuiteTab(Unknown Source)
	at burp.exn.addSuiteTab(Unknown Source)
	at burp.BurpExtender$1.run(BurpExtender.java:292)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.ClassCastException: class com.alibaba.fastjson.JSONArray cannot be cast to class com.alibaba.fastjson.JSONObject (com.alibaba.fastjson.JSONArray and com.alibaba.fastjson.JSONObject are in unnamed module of loader burp.bci @2f1b95d8)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:247)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:535)
	at burp.hs6.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.ClassCastException: class com.alibaba.fastjson.JSONArray cannot be cast to class com.alibaba.fastjson.JSONObject (com.alibaba.fastjson.JSONArray and com.alibaba.fastjson.JSONObject are in unnamed module of loader burp.bci @2f1b95d8)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:247)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:535)
	at burp.hs6.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
com.alibaba.fastjson.JSONException: not close json text, token : int
	at com.alibaba.fastjson.parser.DefaultJSONParser.close(DefaultJSONParser.java:1527)
	at com.alibaba.fastjson.JSON.parse(JSON.java:174)
	at com.alibaba.fastjson.JSON.parse(JSON.java:180)
	at com.alibaba.fastjson.JSON.parse(JSON.java:149)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:241)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:475)
	at burp.hs6.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.ClassCastException: class com.alibaba.fastjson.JSONArray cannot be cast to class com.alibaba.fastjson.JSONObject (com.alibaba.fastjson.JSONArray and com.alibaba.fastjson.JSONObject are in unnamed module of loader burp.bci @2f1b95d8)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:247)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:535)
	at burp.hs6.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
`

**Comment by f0ng** [comment]
这里我是1.8_231的jdk，师傅再多换几次jdk呢

**Comment by f0ng** [comment]
师傅可以到[FAQ](https://github.com/f0ng/log4j2burpscanner/blob/main/FAQ.md#6%E5%AF%BC%E5%85%A5%E6%8F%92%E4%BB%B6%E6%8A%A5%E9%94%99javalangnullpointerexception-cannot-invoke-burpihttprequestresponsegethttpservice-because-thiscurrentlydisplayeditem-is-null)查看解决
