### ISSUE TITLE
ERROR 报错信息

### ISSUE THREAD

**Issue by 0ks3iio** [f0ng/log4j2burpscanner#30]
![image](https://user-images.githubusercontent.com/8078301/146658854-1ee25d64-5eba-4412-997f-bbeb00b73a83.png)
![image](https://user-images.githubusercontent.com/8078301/146658864-7920e596-0ab2-42bc-8873-d6b25f57e8c6.png)
![image](https://user-images.githubusercontent.com/8078301/146658868-a05ec227-7b48-4bc6-bd52-6ee3f0f11b0a.png)

`java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.aii.T(Unknown Source)
	at burp.cnn.getHttpService(Unknown Source)
	at burp.gvg.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:128)
	at burp.bpc.a(Unknown Source)
	at burp.fno.a(Unknown Source)
	at burp.dt2.a(Unknown Source)
	at burp.dt2.a(Unknown Source)
	at burp.jf.a(Unknown Source)
	at burp.guy.a(Unknown Source)
	at burp.dc4.b(Unknown Source)
	at burp.jf.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addImpl(Container.java:1147)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:760)
	at burp.cd6.a(Unknown Source)
	at burp.cd6.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(JTabbedPane.java:834)
	at burp.bxg.a(Unknown Source)
	at burp.guy.c(Unknown Source)
	at burp.guy.a(Unknown Source)
	at burp.ftr.a(Unknown Source)
	at burp.d0t.addSuiteTab(Unknown Source)
	at burp.i78.addSuiteTab(Unknown Source)
	at burp.c04.addSuiteTab(Unknown Source)
	at burp.BurpExtender$1.run(BurpExtender.java:863)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.aii.T(Unknown Source)
	at burp.cnn.getHttpService(Unknown Source)
	at burp.gvg.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:128)
	at burp.bpc.a(Unknown Source)
	at burp.fno.a(Unknown Source)
	at burp.dt2.a(Unknown Source)
	at burp.dt2.a(Unknown Source)
	at burp.jf.a(Unknown Source)
	at burp.guy.a(Unknown Source)
	at burp.dc4.b(Unknown Source)
	at burp.jf.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addNotify(Container.java:2801)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4792)
	at java.desktop/java.awt.Container.addImpl(Container.java:1147)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:760)
	at burp.cd6.a(Unknown Source)
	at burp.cd6.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(JTabbedPane.java:834)
	at burp.bxg.a(Unknown Source)
	at burp.guy.c(Unknown Source)
	at burp.guy.a(Unknown Source)
	at burp.ftr.a(Unknown Source)
	at burp.d0t.addSuiteTab(Unknown Source)
	at burp.i78.addSuiteTab(Unknown Source)
	at burp.c04.addSuiteTab(Unknown Source)
	at burp.BurpExtender$1.run(BurpExtender.java:863)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

`

**Comment by f0ng** [comment]
更换一下`Extender`→`Options`→`Java Environment`下的JDK版本试试

**Comment by SummerSec** [comment]
同样的错误，试了切换JDK版本还是一样。JDK8 9 11 7 6都试过了

**Comment by f0ng** [comment]
我给出我的jdk配置参考一下，感觉可能是小版本的问题

bp环境
![image](https://user-images.githubusercontent.com/48286013/146700638-532c0b5a-1341-4ad0-8ab8-2cef1ed7ac19.png)

bp环境的java版本：
![image](https://user-images.githubusercontent.com/48286013/146700648-4ff952ee-4d00-4bd2-bf38-159076bef820.png)

启动bp的java版本：
![image](https://user-images.githubusercontent.com/48286013/146700699-f3ec328b-c098-417a-a8b5-f09b42684029.png)


编译jar用到的jdk版本：
![image](https://user-images.githubusercontent.com/48286013/146700739-74349e45-71cc-4fd2-b061-f10042ddcc0c.png)


实在不行下载源码本地编译一下

**Comment by f0ng** [comment]
#8 这位师傅换的1.8_202成功了

**Comment by SummerSec** [comment]
![image](https://user-images.githubusercontent.com/47944478/146703338-6b2bb61f-5364-4e7f-aefe-7fe7964dbcc7.png)

![image](https://user-images.githubusercontent.com/47944478/146703351-b145629f-02c0-46b3-8ec6-4ffe68ed292b.png)

还是一样报错

**Comment by SummerSec** [comment]
下载源码自编译还是一样，release下载也是一样。

**Comment by f0ng** [comment]
你好，请问你启动burp的java版本是不是超过了8？提供的tag里面都是使用java1.8进行编译的，所以在高版本的情况下，可能导致导入失败，你可以下载源码使用你同burp的java版本进行编译即可

**Comment by f0ng** [comment]
看下pmiaowu大佬的解答
https://github.com/pmiaowu/BurpFastJsonScan/issues/6

**Comment by f0ng** [comment]
我这里windows低版本bp、低版本windows也可以加载

![image](https://user-images.githubusercontent.com/48286013/146704478-012719e7-cd27-4b16-b2ba-18d0c8bcc54f.png)
<img src="https://user-images.githubusercontent.com/48286013/146704487-345fdb34-9d5f-4939-a345-78c8477dad9b.png" width="550" height="300" />
![image](https://user-images.githubusercontent.com/48286013/146704558-4e95722c-6b8c-4ca7-b9c5-4f2fe9028b2c.png)

**Comment by SummerSec** [comment]
都不行，害。难受

**Comment by f0ng** [comment]
编译的时候修改下pom.xml里的   
`<source>1.8</source>`
`<target>1.8</target>`
改为自有的版本呢，比如mvn的jdk10就是1.10，google了一下感觉都是高版本jdk对低版本jdk编译的jar不兼容的问题

**Comment by f0ng** [comment]
试试看新的releases下的jdk11的jar，我切换了mvn的jdk版本进行打包了

**Comment by Explore-c** [comment]
我跟他一样的问题，1.8.0_161，自己编译和下载release的都不行

**Comment by f0ng** [comment]
用高版本的jdk8试试，实测`1.8_251`、`1.8_231`都可以正常加载
具体和启动burp的jdk也有关系

**Comment by SummerSec** [comment]
![image](https://user-images.githubusercontent.com/47944478/146885138-e4ab6e23-5675-4203-a6e1-0a972624973b.png)

上面报错不影响使用，但运行报错这个，感觉是多线程处理问题？

**Comment by SummerSec** [comment]
工具还有几点建议，这个一个

**Comment by f0ng** [comment]
`0.17.2`版本已添加漏洞参数点报告
