### ISSUE TITLE
手动查看dnslog平台有记录，控制台errors报错，获取不到数据

### ISSUE THREAD

**Issue by GG-o1** [f0ng/log4j2burpscanner#39]
java.lang.NullPointerException: Cannot invoke "okhttp3.Response.body()" because "response2" is null
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1799)
	at burp.g6d.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
![image](https://user-images.githubusercontent.com/32947015/148631239-d5d90164-d286-4241-82eb-ffbc7d76b546.png)

**Comment by f0ng** [comment]
感谢师傅反馈，https://log.xn--9tr.com 网站有时候连通性会断，推荐使用ceye平台或者自建dns记录平台
