### ISSUE TITLE
Not a Bug, just a questions

### ISSUE THREAD

**Issue by Teicu** [f0ng/log4j2burpscanner#40]
Hi again 

What is the difference between  **log4j2burpscanner-0.18.3-jdk11.jar** and **log4j2burpscanner-0.18.3-jdk8.jar**  

What version is better for Mac if my java version in use is "15.0.1" ?  

is it possible instead of ceyedns to make it works with burp collaborator?

Thanks

**Comment by f0ng** [comment]
Hello

The difference between`log4j2burpscanner-0.18.3-jdk11.jar` and ` log4j2burpscanner-0.18.3-jdk8.jar` is that the compiled jdk version is different.

Maybe I think jdk11 is better for you,in fact, I'm not sure, because my `Burp Suite` jdk version is 10.

The delay of burp collaborator is too high for me, so I'm not going to consider it.

Best wishes

**Comment by Teicu** [comment]
Got it, thanks for the reply mate! 

Regards

**Comment by Teicu** [comment]
Ok, just installed  log4j2burpscanner-0.18.3-jdk11.jar and bellow are the errors that I get


java.lang.NullPointerException: Cannot invoke "okhttp3.Response.body()" because "response2" is null
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1894)
	at burp.as_.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.NullPointerException: Cannot invoke "okhttp3.Response.body()" because "response2" is null
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1894)
	at burp.as_.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.NullPointerException: Cannot invoke "okhttp3.Response.body()" because "response2" is null
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1894)
	at burp.as_.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.NullPointerException: Cannot invoke "okhttp3.Response.body()" because "response2" is null
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1894)
	at burp.as_.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.NullPointerException: Cannot invoke "okhttp3.Response.body()" because "response2" is null
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1894)
	at burp.as_.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.NullPointerException: Cannot invoke "okhttp3.Response.body()" because "response2" is null
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1894)
	at burp.as_.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.NullPointerException: Cannot invoke "okhttp3.Response.body()" because "response2" is null
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1894)
	at burp.as_.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
java.lang.NullPointerException: Cannot invoke "okhttp3.Response.body()" because "response2" is null
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1894)
	at burp.as_.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Teicu** [comment]
same errors if I use log4j2burpscanner-0.18.3-jdk8.jar :(

**Comment by Teicu** [comment]
<img width="951" alt="Screenshot 2022-01-10 at 16 12 35" src="https://user-images.githubusercontent.com/1572822/148779951-b5ed1ebe-574c-495a-b084-a5b86c964bce.png">

**Comment by f0ng** [comment]
Line `1894` code is ceyedns,I guess it's  delay of `ceye.io` is too high,like #39,but his problem is that the default  dns platform delay is too high, u can try to  change the dns platform
You can even build a DNS platform yourself  [DNSLog-Platform-Golang](https://github.com/yumusb/DNSLog-Platform-Golang)

**Comment by Teicu** [comment]
I'll try it now, thank you
