### ISSUE TITLE
Mac error

### ISSUE THREAD

**Issue by Teicu** [f0ng/log4j2burpscanner#46]
Hi, Any idea why I'm getting these errors? I use the latest version of your extension 

Macbook  

Java(TM) SE Runtime Environment (build 15.0.1+9-18)
JDK (build 1.8.0_321-b07)

```

java.lang.ClassCastException: class com.alibaba.fastjson.JSONArray cannot be cast to class com.alibaba.fastjson.JSONObject (com.alibaba.fastjson.JSONArray and com.alibaba.fastjson.JSONObject are in unnamed module of loader burp.ei4 @7034e82d)
java.lang.ClassCastException: class com.alibaba.fastjson.JSONArray cannot be cast to class com.alibaba.fastjson.JSONObject (com.alibaba.fastjson.JSONArray and com.alibaba.fastjson.JSONObject are in unnamed module of loader burp.ei4 @7034e82d)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:259)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:259)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1467)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:1467)
	at burp.dbq.run(Unknown Source)
	at burp.dbq.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
Thanks

**Comment by Teicu** [comment]
Also does not work "Send to log4j2 scanner". Whatever application request I send, I don't see anything that makes it to the scanner

**Comment by f0ng** [comment]
oh,the `java.lang.ClassCastException` error didn't affect the use of the extension，because some formats may not be recognized, such as binary files
the `does not work "Send to log4j2 scanner"` maybe u can change the jdk version or there is a conflicting extension，for example, `Hae` could cause conflict  #37
