### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by securit123** [f0ng/log4j2burpscanner#8]
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.gpz.P(Unknown Source)
	at burp.dzg.getHttpService(Unknown Source)
	at burp.gn0.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:151)
	at burp.cio.a(Unknown Source)
	at burp.fjz.a(Unknown Source)
	at burp.fjz.a(Unknown Source)
	at burp.a_p.a(Unknown Source)
	at burp.g8.b(Unknown Source)
	at burp.fjz.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1009)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:453)
	at burp.fjo.d(Unknown Source)
	at burp.fjo.b(Unknown Source)
	at burp.fjo.a(Unknown Source)
	at burp.fjo.lambda$layoutInitialised$2(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.gpz.P(Unknown Source)
	at burp.dzg.getHttpService(Unknown Source)
	at burp.gn0.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:151)
	at burp.cio.a(Unknown Source)
	at burp.fjz.a(Unknown Source)
	at burp.fjz.a(Unknown Source)
	at burp.a_p.a(Unknown Source)
	at burp.g8.b(Unknown Source)
	at burp.fjz.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1009)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:453)
	at burp.fjo.d(Unknown Source)
	at burp.fjo.b(Unknown Source)
	at burp.fjo.a(Unknown Source)
	at burp.fjo.lambda$layoutInitialised$2(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by f0ng** [comment]
感谢反馈，是加载插件的时候遇到的，还是扫描的时候遇到的

**Comment by securit123** [comment]
加载插件的时候

**Comment by f0ng** [comment]
应该和jdk版本有关，显示无法调用"burp.IHttpRequestResponse.getHttpService()"，师傅换换jdk试试呢，Options→Java Environment那里配置

**Comment by securit123** [comment]
解决了。但是好像这个不准呀，有log4j漏洞的，没有识别出来

**Comment by f0ng** [comment]
具体是什么情况，可以把请求包给我看看吗，还是很取决于本地网络环境与dnslog平台的连通性的，可以尝试更换其他dnslog平台试试

**Comment by ketchup1995** [comment]
> 解决了。但是好像这个不准呀，有log4j漏洞的，没有识别出来

师傅是怎么解决的，换的哪个版本

**Comment by securit123** [comment]
jdk1.8.0_202

**Comment by securit123** [comment]
倒是识别出来了，但是反应好慢

**Comment by f0ng** [comment]
是的，请求头多了、长了都会影响检测的速率，还有就是与dnslog的连通性；
只能牺牲其他请求头，延长dnslog平台的响应时间来换取漏洞的准确性了，就会造成反应慢
